"""
CUDA Open Compiler - Lowering Passes & Code Generation

Transforme l'IR de haut niveau (OpenIR) en opérations GPU de bas niveau.
C'est ici que les optimisations "Neuro-Symboliques" sont appliquées.
"""

from .openir import *
from .backends import get_all_backends
import hashlib

class LoweringPass:
    def run(self, module: Module):
        raise NotImplementedError

class TurboQuantFusionPass(LoweringPass):
    """
    Détecte les patterns `matmul -> add -> relu` et les fusionne en un seul 
    noyau optimisé `turbo_quant_fused_kernel`.
    """
    def run(self, module: Module):
        print("  🧠 [Pass] TurboQuant Fusion...")
        fused_count = 0
        
        # Analyse simple du graphe pour trouver des chains
        for block in module.region.blocks:
            ops_to_remove = []
            for i, op in enumerate(block.operations):
                # Chercher un matmul
                if op.name == "open.matmul":
                    # Vérifier si le résultat est utilisé par un add
                    res_val = op.results[0]
                    if len(res_val.uses) == 1:
                        user_op = res_val.uses[0]
                        if user_op.name == "open.add":
                            # On a trouvé MatMul -> Add. On peut fusionner.
                            # Créer le nouvel op fusionné
                            bias_val = user_op.operands[1] # Le bias est le 2eme operand de add
                            
                            fused_op = Op(
                                name="open.cuda.turbo_quant_matmul",
                                operands=[op.operands[0], op.operands[1], bias_val],
                                results=user_op.results, # Le résultat final reste le même
                                attributes={"fused": "true", "bits": 4, "group_size": 128}
                            )
                            
                            # Remplacer dans le bloc
                            block.operations[i] = fused_op
                            block.operations.remove(user_op)
                            ops_to_remove.append(op)
                            
                            # Mettre à jour les liens
                            fused_op.results[0].defining_op = fused_op
                            fused_count += 1
                            
        if fused_count > 0:
            print(f"     ✅ {fused_count} noyaux fusionnés (TurboQuant)")
        else:
            print(f"     ℹ️ Aucune fusion possible détectée.")

class MemoryPlanningPass(LoweringPass):
    """
    Alloue virtuellement les buffers et décide des placements mémoire 
    (Global vs Shared vs Registers).
    """
    def run(self, module: Module):
        print("  🧠 [Pass] Memory Planning...")
        # Simulation : on marque les tenseurs pour le shared memory si petits
        for block in module.region.blocks:
            for op in block.operations:
                if "matmul" in op.name or "turbo" in op.name:
                    op.attributes["mem_layout"] = "optimized_tiled"
        print(f"     ✅ Planification mémoire terminée.")

class CodeGenPass(LoweringPass):
    """
    Génère le code source pour TOUTES les cibles (CUDA, HIP, SYCL, CPU).
    """
    def run(self, module: Module) -> Dict[str, str]:
        print("  📝 [Pass] Multi-Target Code Generation...")
        
        generated_sources = {}
        
        for backend in get_all_backends():
            lines = []
            # En-tête spécifique
            lines.append(f"// ---------------------------------------------------------")
            lines.append(f"// Auto-generated by CUDA Open Compiler ({module.name})")
            lines.append(f"// Target: {backend.name}")
            lines.append(f"// ---------------------------------------------------------")
            lines.extend(backend.headers)
            lines.append("")
            
            # Inclusion des types et utilitaires
            lines.append("#include <stdint.h>")
            lines.append("")

            # Génération des kernels
            for block in module.region.blocks:
                for op in block.operations:
                    if op.name == "open.cuda.turbo_quant_matmul":
                        lines.extend(self._generate_turbo_quant_kernel(backend, op))
                    elif op.name == "open.matmul":
                        lines.extend(self._generate_standard_kernel(backend, op))
            
            generated_sources[backend.name] = "\n".join(lines)
            
        return generated_sources

    def _generate_turbo_quant_kernel(self, backend, op):
        """Génère un kernel C++ optimisé pour la cible donnée."""
        lines = []
        lines.append(f"// Kernel: TurboQuant MatMul + Add")
        lines.append(f"{backend.kernel_macro} turbo_quant_matmul_{backend.name.replace(' ', '_').lower()}(")
        lines.append(f"    const uint8_t* W_int4, const float* Scales, const float* B, const float* Bias, float* Output, int M, int K, int N")
        lines.append(f") {{")
        lines.append(f"    int idx = {backend.grid_macro};")
        lines.append(f"    int total_elements = M * N;")
        lines.append(f"")
        lines.append(f"    if (idx < total_elements) {{")
        lines.append(f"        int row = idx / N;")
        lines.append(f"        int col = idx % N;")
        lines.append(f"")
        lines.append(f"        float sum = 0.0f;")
        lines.append(f"")
        lines.append(f"        // Boucle sur K (Déquantification à la volée + Accumulation)")
        lines.append(f"        for (int k = 0; k < K; k++) {{")
        lines.append(f"            // 1. Charger et déquantifier W (INT4 -> Float)")
        lines.append(f"            int byte_idx = (row * K + k) / 2;")
        lines.append(f"            uint8_t packed = W_int4[byte_idx];")
        lines.append(f"            int4_val = ((k % 2 == 0) ? (packed & 0x0F) : ((packed >> 4) & 0x0F)) - 8;")
        lines.append(f"")
        lines.append(f"            // 2. Appliquer le scale du groupe (Simulation: scale constant ici)")
        lines.append(f"            float w_fp32 = (float)int4_val * 0.1f; // Fake scale")
        lines.append(f"")
        lines.append(f"            // 3. FMA (Fused Multiply Add)")
        lines.append(f"            sum += w_fp32 * B[k * N + col];")
        lines.append(f"        }}")
        lines.append(f"")
        lines.append(f"        // 4. Ajout du Bias et écriture")
        lines.append(f"        Output[row * N + col] = sum + Bias[row];")
        lines.append(f"    }}")
        lines.append(f"}}")
        lines.append("")
        return lines

    def _generate_standard_kernel(self, backend, op):
        """Génère un kernel standard."""
        lines = []
        lines.append(f"{backend.kernel_macro} standard_matmul_{backend.name.replace(' ', '_').lower()}(")
        lines.append(f"    const float* A, const float* B, float* C, int M, int K, int N")
        lines.append(f") {{")
        lines.append(f"    int idx = {backend.grid_macro};")
        lines.append(f"    if (idx < M * N) {{")
        lines.append(f"        int row = idx / N;")
        lines.append(f"        int col = idx % N;")
        lines.append(f"        float sum = 0.0f;")
        lines.append(f"        for (int k = 0; k < K; ++k) {{")
        lines.append(f"            sum += A[row * K + k] * B[k * N + col];")
        lines.append(f"        }}")
        lines.append(f"        C[row * N + col] = sum;")
        lines.append(f"    }}")
        lines.append(f"}}")
        lines.append("")
        return lines
